import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Ahmed",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "john",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: "1",
      name: "casio metal watch",
      slug: "casio-metal-watch",
      category: "Mens",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 100,
      brand: "Casio",
      rating: "4.5",
      numReviews: 10,
      description: "high quality watch",
    },
    {
      // _id: "2",
      name: "casio gshock watch",
      slug: "casio-gshock-watch",
      category: "Mens",
      image: "/images/p2.jpg",
      price: 250,
      countInStock: 0,
      brand: "Casio",
      rating: "4.5",
      numReviews: 10,
      description: "high quality watch",
    },
    {
      // _id: "3",
      name: "casio leather watch",
      slug: "casio-leather-watch",
      category: "Mens",
      image: "/images/p3.jpg",
      price: 25,
      countInStock: 15,
      brand: "Casio",
      rating: "4.5",
      numReviews: 10,
      description: "high quality watch",
    },
    {
      // _id: "4",
      name: "casio women watch",
      slug: "casio-women-watch",
      category: "Mens",
      image: "/images/p4.jpg",
      price: 65,
      countInStock: 5,
      brand: "Casio",
      rating: "4.5",
      numReviews: 10,
      description: "high quality watch",
    },
  ],
};
export default data;

