const data = {
  products: [
    {
      name: "casio metal watch",
      slug: "casio-metal-watch",
      category: "Mens",
      image: "/images/p1.jpg",
      price: 120,
      brand: "Casio",
      rating: "4.5",
      numReviews: 10,
      description: "high quality watch",
    },
    {
      name: "casio gshock watch",
      slug: "casio-gshock-watch",
      category: "Mens",
      image: "/images/p2.jpg",
      price: 250,
      brand: "Casio",
      rating: "4.5",
      numReviews: 10,
      description: "high quality watch",
    },
    {
      name: "casio leather watch",
      slug: "casio-leather-watch",
      category: "Mens",
      image: "/images/p3.jpg",
      price: 25,
      brand: "Casio",
      rating: "4.5",
      numReviews: 10,
      description: "high quality watch",
    },
    {
      name: "casio women watch",
      slug: "casio-women-watch",
      category: "Mens",
      image: "/images/p4.jpg",
      price: 65,
      brand: "Casio",
      rating: "4.5",
      numReviews: 10,
      description: "high quality watch",
    },
  ],
};
export default data;
